apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceconfigs.namespaceconfig.ei.com
spec:
  group: namespaceconfig.ei.com
  names:
    kind: Namespaceconfig
    listKind: NamespaceconfigList
    plural: namespaceconfigs
    singular: namespaceconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
