---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespaceconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespaceconfig
  template:
    metadata:
      labels:
        name: namespaceconfig
    spec:
      serviceAccountName: namespaceconfig
      containers:
        - name: namespaceconfig
          # Replace this with the built image name
          image: "quay.io/saberkan/namespaceconfig:v0.0.1"
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: '1'
              memory: 500Mi
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespaceconfig"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
